BD_polls/DB_project/urls.py
from __future__ import print_function
from cms.sitemaps import CMSSitemap
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings
import questions_and_ratings.urls

admin.autodiscover()

urlpatterns = i18n_patterns('',
                            url(r'^admin/', include(admin.site.urls)),  # NOQA
                            url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
                                {'sitemaps': {'cmspages': CMSSitemap}}),
                            url(r'^questions_and_ratings/', include(questions_and_ratings.urls)),
                            url(r'^', include('social.apps.django_app.urls', namespace='social')),
                            url(r'^login/$', 'views.login'),
                            url(r'^logout/$', 'views.logout'),
                            url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
                           url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
                               {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

BD_polls/questions_and_ratings/urls.py
from django.conf.urls import patterns, url
from .views import question_view, rating_view


urlpatterns = patterns('',
                       url(r'^question/(?P<question_id>\d+)$', question_view, name='question'),
                       url(r'^rating/(?P<rating_id>\d+)$', rating_view, name='rating'),
)

BD_polls/raports/urls.py
from django.conf.urls import *
from raports import views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^generate', views.generate, name='generate'),
    url(r'^$', views.sview, name='raports'),
)

BD_polls/questions_and_ratings/models.py
from cms.models import CMSPlugin
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class QuestionRatingMixin(models.Model):
    start = models.DateTimeField(default=timezone.now())
    end = models.DateTimeField()
    show_results_before_end = models.BooleanField(default=False)
    text = models.CharField(max_length=200)

    def __unicode__(self):
        return self.text

    def is_active(self):
        return timezone.now() <= self.end

    class Meta:
        abstract = True


class VoteMixin(models.Model):
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField(default=timezone.now())

    class Meta:
        abstract = True


class Question(QuestionRatingMixin):
    multiple_answers = models.BooleanField(default=False)

    def get_results(self):
        if self.show_results_before_end or not self.is_active():
            answers = QuestionAnswer.objects.filter(question=self)
            return dict((answer.text, answer.questionvote_set.count()) for answer in answers)
        else:
            return None


class QuestionAnswer(models.Model):
    question = models.ForeignKey(Question)
    text = models.CharField(max_length=200)


class QuestionVote(VoteMixin):
    answers = models.ManyToManyField(QuestionAnswer)

    @staticmethod
    def votes(question, user):
        return QuestionVote.objects.filter(answers__question=question, user=user)


class Rating(QuestionRatingMixin):
    max = models.IntegerField()
    TYPES = (
        ("STARS", "stars rating"),
        ("SLIDER", "slider rating"),
        ("LIKES", "like rating"),
    )
    type = models.CharField(max_length=10, choices=TYPES)

    def get_results(self):
        if self.show_results_before_end or not self.is_active():
            return dict((i, self.ratingvote_set.filter(value=i).count()) for i in range(1, self.max + 1))
        else:
            return None


class RatingVote(VoteMixin):
    rating = models.ForeignKey(Rating)
    value = models.IntegerField()

    @staticmethod
    def votes(rating, user):
        return RatingVote.objects.filter(rating=rating, user=user)


class QuestionPlugin(CMSPlugin):
    question = models.ForeignKey(Question)


class RatingPlugin(CMSPlugin):
    rating = models.ForeignKey(Rating)

BD_polls/raports/models.py
from django.db import models

# Create your models here.

BD_polls/DB_project/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import logout as auth_logout
# from django.template.context import RequestContext


def login(request):
    return render(request, 'login.html')


def logout(request):
    auth_logout(request)
    return redirect('/')

BD_polls/questions_and_ratings/views.py
import json

from django.core.exceptions import PermissionDenied
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_http_methods
from questions_and_ratings.models import Question, QuestionVote, QuestionAnswer, Rating, RatingVote


@require_http_methods(["POST"])
def question_view(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        answers = request.POST.getlist("answers")
        if answers:
            answers = [get_object_or_404(QuestionAnswer, pk=int(answer)) for answer in answers]
            if QuestionVote.votes(question, request.user):
                raise PermissionDenied()
            vote = QuestionVote(user=request.user)
            vote.save()
            vote.answers.add(*answers)
            return HttpResponse(json.dumps(question.get_results()))
        else:
            vote = QuestionVote.votes(question, request.user)
            vote.delete()
            return HttpResponse(json.dumps(question.get_results()))


@require_http_methods(["POST"])
def rating_view(request, rating_id):
    rating = get_object_or_404(Rating, pk=rating_id)
    if request.method == "POST":
        answers = request.POST.getlist("answers")
        if answers:
            if RatingVote.votes(rating, request.user):
                raise PermissionDenied()
            vote = RatingVote(rating=rating, value=int(answers[0]), user=request.user)
            vote.save()
            return HttpResponse(json.dumps(rating.get_results()))
        else:
            vote = RatingVote.votes(rating, request.user)
            vote.delete()
            return HttpResponse(json.dumps(rating.get_results()))

BD_polls/raports/views.py
from django.shortcuts import get_object_or_404, render
from questions_and_ratings.models import Question, Rating


def sview(request):
    q = Question.objects.all()
    r = Rating.objects.all()
    dictionary = {'qs': q, 'rs': r}
    return render(request, 'raports/templates/raports.html', dictionary)


def generate(request):
    qs = Question.objects.all()
    q_list = []
    for q in qs:
        is_on = request.GET.get(str(q.id), 'f')
        if is_on == "on":
            q_list.append(q.id)
    rs = Rating.objects.all()
    for r in rs:
        is_on = request.GET.get('r' + str(r.id), 'f')
        if is_on == "on":
            q_list.append(-r.id)
    wanted_results = []
    for pk in q_list:
        if pk > 0:
            q = get_object_or_404(Question, pk=pk)
        else:
            q = get_object_or_404(Rating, pk=-pk)
        infos = []
        results = q.get_results()
        for key, value in results.iteritems():
            infos.append((key, value))
        wanted_results.append((q, infos))
    print wanted_results
    dictionary = {'results': wanted_results}
    return render(request, 'raports/templates/results.html', dictionary)

BD_polls/DB_project/templates/base.html
{% load cms_tags staticfiles sekizai_tags menu_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}This is my new project home page{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% render_block "css" %}
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">
    <script src="http://code.jquery.com/jquery.js"></script>

<script src="http://code.jquery.com/jquery.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
</head>
<body style="padding-top:60px">
{% cms_toolbar %}
<div class="container">
    {% if user and not user.is_anonymous %}
        <a href="/logout" backgrou><img src="/media/logout-button-blue-hi.png"></a>
    {% else %}
        <a href="{% url 'social:begin' 'usosweb' %}?next={{ request.path }}">Login with Usosweb</a>
    {% endif %}
    <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% show_menu 0 1 100 100 "menu.html" %}
            </ul>
        </div>
    </div>
    {% block content %}
    {% endblock content %}
</div>
{% render_block "js" %}
</body>
</html>

BD_polls/DB_project/templates/feature.html
{% extends "base.html" %}
{% load cms_tags staticfiles sekizai_tags menu_tags %}

{% block content %}
<div class="jumbotron">
  {% placeholder "feature" %}
</div>
<div>
  {% placeholder "content" %}
</div>
{% endblock content %}

BD_polls/DB_project/templates/login.html
{% extends "base.html" %}
{% block content %}
    {% if user and not user.is_anonymous %}
        <a>Hello, {{ user.get_full_name }}!</a>
        <br>
        <a href="/logout">Logout</a>
    {% else %}
        <a href="{% url 'social:begin' 'usosweb' %}?next={{ request.path }}">Login with Usosweb</a>
    {% endif %}
{% endblock %}

BD_polls/DB_project/templates/menu.html
{% load i18n menu_tags cache %}

{% for child in children %}


<li class="{% if child.ancestor %}ancestor{% endif %}{% if child.selected %} active{% endif %}{% if child.children %} dropdown{% endif %}">
    {% if child.children %}<a class="dropdown-toggle" data-toggle="dropdown" href="#">{{ child.get_menu_title }} <span class="caret"></span></a>
    <ul class="dropdown-menu">
        {% show_menu from_level to_level extra_inactive extra_active template "" "" child %}
    </ul>
    {% else %}
    <a href="{{ child.get_absolute_url }}"><span>{{ child.get_menu_title }}</span></a>
    {% endif %}
</li>

{% if class and forloop.last and not forloop.parentloop %}
{% endif %}
{% endfor %}

BD_polls/DB_project/templates/page.html
{% extends "base.html" %}
{% load cms_tags staticfiles sekizai_tags menu_tags %}

{% block content %}
<div>
  {% placeholder "content" %}
</div>
{% endblock content %}

BD_polls/questions_and_ratings/templates/question.html
{% load sekizai_tags cms_tags %}
{% if user and not user.is_anonymous %}
    <h1>{% render_model question "text" %}</h1>
    <div id="question_form_{{ question.id }}">
        <form id="question_form" style="display: {{ results|yesno:"none,block" }}">
            {% for answer in question.questionanswer_set.all %}
                <input type="{{ question.multiple_answers|yesno:"checkbox,radio" }}" name="answers"
                       id="answer{{ forloop.counter }}" value="{{ answer.id }}" _text="{{ answer.text }}"/>
                <label for="answer{{ forloop.counter }}">{{ answer.text }}</label>
                <br/>
            {% endfor %}
            <input type="submit" class="btn btn-default"/>
        </form>
    </div>
    <div id="question_answers_{{ question.id }}" style="display: {{ results|yesno:"block, none" }}">
        {% if results %}
            {% for key, value in results.iteritems %}
                <p>{{ key }}:{{ value }}</p>
            {% endfor %}
        {% endif %}
    </div>
    <script>
        var func{{ question.id }} = function () {
            var form = $("#question_form_" + {{ question.id }} +" > form");
            var answers = $("#question_answers_" +{{ question.id }});
            var show_form = function () {
                answers.css("display", "none");
                form.css("display", "block");
            };
            var show_answers = function () {
                form.css("display", "none");
                answers.css("display", "block");
                checked = [];
                form.children("input").each(function () {
                    if ($(this).prop('checked')) {
                        checked.push($(this).attr("_text"));
                    }
                });
                console.log(checked);
                answers.children("p").each(function () {
                    if (checked.indexOf($(this).text().split(":")[0]) != -1) {
                        $(this).css("font-weight", "bold");
                    }
                });
            };
            var cancelButton = $('<button class="btn btn-default">').text("Cancel Vote").click(
                    function () {
                        $.ajax({
                            type: "POST",
                            url: "{% url 'question' question.id %}",
                            success: show_form
                        });
                    }
            );
            {% if results %}
                answers.append(cancelButton);
            {% endif %}
            var populate_results = function (data) {
                show_answers();
                var results = JSON.parse(data);
                answers.empty();
                for (var option in results) {
                    answers.append($('<p>').text(option + ':' + results[option]));
                }
                answers.append($('<button class="btn btn-default">').text("Cancel Vote").click(
                        function () {
                            $.ajax({
                                type: "POST",
                                url: "{% url 'question' question.id %}",
                                success: show_form
                            });
                        }
                ));
            };
            $("#question_form_" + {{ question.id }}).submit(function (event) {
                $.ajax({
                    type: "POST",
                    url: "{% url 'question' question.id %}",
                    data: form.serialize(),
                    success: populate_results,
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        answers.empty();
                        answers.append($('<p>').text(errorThrown));
                        answers.append(cancelButton);
                    }
                });
                event.preventDefault();
            });
        };
        func{{ question.id }}();
    </script>
{% else %}
    <h2>{{ question.text }}</h2>
    <h4>The user is not logged in. You should log in.</h4>
{% endif %}

BD_polls/questions_and_ratings/templates/rating.html
{% load sekizai_tags cms_tags %}
{% if user and not user.is_anonymous %}
    <h1>{% render_model rating "text" %}</h1>
    <div id="rating_form_{{ rating.id }}" style="display: {{ results|yesno:"none, block" }}">
        {% if rating.type == "SLIDER" %}
            <p>
                <label for="rating{{ rating.id }}">Value:</label>
                <input type="text" id="rating{{ rating.id }}" style="border:0; font-weight:bold;" value="1">
            </p>

            <div id="slider{{ rating.id }}"></div>
            <button class="btn btn-default">Submit</button>
        {% else %}
            <form id="rating_form">
                <fieldset class="stars_rating">
                    <legend>Please rate:</legend>
                    <input type="radio" id="star5" name="answers" value="5"/>
                    <label for="star5" title="Rocks!">5 stars</label>
                    <input type="radio" id="star4" name="answers" value="4"/>
                    <label for="star4" title="Pretty good">4 stars</label>
                    <input type="radio" id="star3" name="answers" value="3"/>
                    <label for="star3" title="Meh">3 stars</label>
                    <input type="radio" id="star2" name="answers" value="2"/>
                    <label for="star2" title="Kinda bad">2 stars</label>
                    <input type="radio" id="star1" name="answers" value="1"/>
                    <label for="star1" title="Sucks big time">1 star</label>
                </fieldset>
                <input type="submit" class="btn btn-default"/>
            </form>
            <br>
        {% endif %}
    </div>
    <div id="rating_answers_{{ rating.id }}" style="display: {{ results|yesno:"block, none" }}">
        {% if results %}
            {% for key, value in results.iteritems %}
                <p>{{ key }}:{{ value }}</p>
            {% endfor %}
        {% endif %}
    </div>
    {% addtoblock "css" %}
        <style>
            .stars_rating {
                float: left;
            }

            /* :not(:checked) is a filter, so that browsers that don’t support :checked don’t
               follow these rules. Every browser that supports :checked also supports :not(), so
               it doesn’t make the test unnecessarily selective */
            .stars_rating:not(:checked) > input {
                position: absolute;
                top: -9999px;
                clip: rect(0, 0, 0, 0);
            }

            .stars_rating:not(:checked) > label {
                float: right;
                width: 1em;
                padding: 0 .1em;
                overflow: hidden;
                white-space: nowrap;
                cursor: pointer;
                font-size: 200%;
                line-height: 1.2;
                color: #ddd;
                text-shadow: 1px 1px #bbb, 2px 2px #666, .1em .1em .2em rgba(0, 0, 0, .5);
            }

            .stars_rating:not(:checked) > label:before {
                content: '★ ';
            }

            .stars_rating > input:checked ~ label {
                color: #f70;
                text-shadow: 1px 1px #c60, 2px 2px #940, .1em .1em .2em rgba(0, 0, 0, .5);
            }

            .stars_rating:not(:checked) > label:hover,
            .stars_rating:not(:checked) > label:hover ~ label {
                color: gold;
                text-shadow: 1px 1px goldenrod, 2px 2px #B57340, .1em .1em .2em rgba(0, 0, 0, .5);
            }

            .stars_rating > input:checked + label:hover,
            .stars_rating > input:checked + label:hover ~ label,
            .stars_rating > input:checked ~ label:hover,
            .stars_rating > input:checked ~ label:hover ~ label,
            .stars_rating > label:hover ~ input:checked ~ label {
                color: #ea0;
                text-shadow: 1px 1px goldenrod, 2px 2px #B57340, .1em .1em .2em rgba(0, 0, 0, .5);
            }

            .stars_rating > label:active {
                position: relative;
                top: 2px;
                left: 2px;
            }
        </style>
    {% endaddtoblock %}
    {% addtoblock "js" %}
        <script>
            var func{{ rating.id }} = function () {
                var form = $("#rating_form_" + {{ rating.id }});
                var answers = $("#rating_answers_" +{{ rating.id }});
                var show_form = function () {
                    answers.css("display", "none");
                    form.css("display", "block");
                };
                var show_answers = function () {
                    form.css("display", "none");
                    answers.css("display", "block");
                };
                var cancelButton = $('<button class="btn btn-default">').text("Cancel Vote").click(
                        function () {
                            $.ajax({
                                type: "POST",
                                url: "{% url 'rating' rating.id %}",
                                success: show_form
                            });
                        }
                );
                {% if results %}
                    answers.append(cancelButton);
                {% endif %}
                var populate_results = function (data) {
                    show_answers();
                    var results = JSON.parse(data);
                    answers.empty();
                    for (var option in results) {
                        answers.append($('<p>').text(option + ':' + results[option]));
                    }
                    answers.append($('<button class="btn btn-default">').text("Cancel Vote").click(
                            function () {
                                $.ajax({
                                    type: "POST",
                                    url: "{% url 'rating' rating.id %}",
                                    success: show_form
                                });
                            }
                    ));
                };
                $(function () {
                    $("#slider" +{{ rating.id }}).slider({
                        min: 1,
                        max: {{ rating.max }},
                        animate: true,
                        slide: function (event, ui) {
                            $("#rating" +{{ rating.id }}).val(ui.value);
                        }
                    });
                });
                {% if rating.type == "SLIDER" %}
                    form.select("button").click(function (event) {
                        $.ajax({
                            type: "POST",
                            url: "{% url 'rating' rating.id %}",
                            data: {"answers": $("#slider" +{{ rating.id }}).slider("option", "value")},
                            success: populate_results,
                            error: function (XMLHttpRequest, textStatus, errorThrown) {
                                answers.empty();
                                answers.append($('<p>').text(errorThrown));
                                answers.append(cancelButton);
                            }
                        });
                    });
                {% else %}
                    form.children().submit(function (event) {
                        $.ajax({
                            type: "POST",
                            url: "{% url 'rating' rating.id %}",
                            data: {"answers": form.children().serialize().substr(8)},
                            success: populate_results,
                            error: function (XMLHttpRequest, textStatus, errorThrown) {
                                answers.empty();
                                answers.append($('<p>').text(errorThrown));
                                answers.append(cancelButton);
                            }
                        });
                        event.preventDefault();
                    });
                {% endif %}
            };
            func{{ rating.id }}();
        </script>
    {% endaddtoblock %}
{% else %}
    <h2>{{ rating.text }}</h2>
    <h4>The user is not logged in. You should log in.</h4>
{% endif %}

BD_polls/raports/templates/base.html
{% load cms_tags staticfiles sekizai_tags menu_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}This is my new project home page{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% render_block "css" %}
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">
    <script src="http://code.jquery.com/jquery.js"></script>
</head>
<body style="padding-top:60px">
{% cms_toolbar %}
<div class="container">
    {% if user and not user.is_anonymous %}
        <a href="/logout" backgrou><img src="/media/gtfo.jpg"></a>
    {% endif %}
    <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Raporty</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% show_menu 0 1 100 100 "menu.html" %}
            </ul>
        </div>
    </div>
    {% block content %}
    {% endblock content %}
</div>
<script src="http://code.jquery.com/jquery.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
{% render_block "js" %}
</body>
</html>

BD_polls/raports/templates/raports.html
{% extends 'base.html' %}
{% block title %}Raport{% endblock%}
{% block content %}
<ul>
<br/>


<form action="{% url 'generate' %}" method="get">
    <h2> Wybierz głosowania, które <br>mają być uwzględnione w raporcie:</h2>
    {% for q in qs %}
        <input type="checkbox" name="{{ q.id }}" /> {{ q.text }} <br />
    {% endfor %}
    {% for r in rs %}
        <input type="checkbox" name="r{{ r.id }}" /> {{ r.text }} <br />
    {% endfor %}
    <br/>
    <input type="submit" class="btn btn-default" value="Wygeneruj raport">
</form>
{% endblock %}
</ul>

BD_polls/raports/templates/results.html
{% extends 'base.html' %}
{% block title %}Raport{% endblock %}
{% block content %}
    <ul>
    <br/>
    <form action="{% url 'generate' %}" method="get">..

        <h2> Oto wyniki raportu:</h2>
        {% for q in results %}
            <h3><b>{{ q.0 }}</b></h3>
		<div id="container{{forloop.counter}}" style="min-width: 500px; height: 400px; margin: 0 auto"></div>
		<script>
			$(function () {
    $('#container{{forloop.counter}}').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: '{{q.0}}'
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Votes'
            }
        },
        legend: {
            enabled: false
        },
        series: [{
            data: [
		{% for ans in q.1 %}
			[{{ans.0}}, {{ans.1}}],
		{% endfor %}
            ],
            dataLabels: {
                enabled: true,
                rotation: -90,
                color: '#FFFFFF',
                align: 'right',
                x: 4,
                y: 10,
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif',
                    textShadow: '0 0 3px black'
                }
            }
        }]
    });
});
		</script>            
        {% endfor %}
        <br/>
    </form>
{% endblock %}
</ul>